<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Karzoun.RelayGrid.Postgres.Tests</AssemblyName>
    <RootNamespace>Karzoun.RelayGrid.Postgres.Tests</RootNamespace>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/RelayGrid.Postgres/RelayGrid.Postgres.csproj" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
  </ItemGroup>
</Project>
